// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTasoMz8zus6DTRwCvu4_sA7NxX679pyQ',
    appId: '1:583301066696:web:039faac4f7892ba0291afd',
    messagingSenderId: '583301066696',
    projectId: 'globe-app-8da95',
    authDomain: 'globe-app-8da95.firebaseapp.com',
    storageBucket: 'globe-app-8da95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqtw1QTWcMqhlEQALlslw0pkgSJqvADyU',
    appId: '1:583301066696:android:6befc645b87f50b1291afd',
    messagingSenderId: '583301066696',
    projectId: 'globe-app-8da95',
    storageBucket: 'globe-app-8da95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0-artpfy0_g-aI89nSkthstrnJKQdVJc',
    appId: '1:583301066696:ios:296838a1af16cf53291afd',
    messagingSenderId: '583301066696',
    projectId: 'globe-app-8da95',
    storageBucket: 'globe-app-8da95.firebasestorage.app',
    iosBundleId: 'com.example.globeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0-artpfy0_g-aI89nSkthstrnJKQdVJc',
    appId: '1:583301066696:ios:296838a1af16cf53291afd',
    messagingSenderId: '583301066696',
    projectId: 'globe-app-8da95',
    storageBucket: 'globe-app-8da95.firebasestorage.app',
    iosBundleId: 'com.example.globeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTasoMz8zus6DTRwCvu4_sA7NxX679pyQ',
    appId: '1:583301066696:web:c4cded62e1a9e94b291afd',
    messagingSenderId: '583301066696',
    projectId: 'globe-app-8da95',
    authDomain: 'globe-app-8da95.firebaseapp.com',
    storageBucket: 'globe-app-8da95.firebasestorage.app',
  );

}